server {
	listen 8080;
	host 0.0.0.0;
	server_name localhost;

	root ./var/www/web;
	index  showcase.html;

	client_max_body_size 10M;

	error_page 400 error/400.html;
	error_page 403 error/403.html;
	error_page 404 error/404.html;
	error_page 500 error/500.html;
	error_page 502 error/502.html;
	error_page 503 error/503.html;

	location / {
		methods GET;
		autoindex off;
	}

	location /web {
		methods GET;
		autoindex on;
	}

	location /uploads {
		methods GET POST DELETE;
		root ./var/www/uploads;
		upload_store ./var/www/uploads;
		autoindex on;
	}

	location /cgi {
		methods GET POST;
		cgi_extension .py /usr/bin/python3;
		#cgi_extension .php /usr/bin/php-cgi;
		cgi_extension .sh /bin/bash;
		root ./var/www/cgi/cgi-bin;
	}

	location /redirect {
		return 301 http://localhost:4242/;
	}
}

server {
	listen 4242;
	host 0.0.0.0;
	server_name webserv;

	root ./var/www/web;
	index yaaqoub.html;

	client_max_body_size 5M;

	error_page 403 /403.html;
	error_page 404 /404.html;
	error_page 500 /500.html;

	location / {
		methods GET;
		autoindex off;
	}

	location /uploads {
		methods GET POST DELETE;
		root ./var/www/uploads;
		upload_store ./var/www/uploads;
		autoindex on;
	}

	location /cgi {
		methods GET POST;
		cgi_extension .py /usr/bin/python3;
		root ./var/www/cgi/cgi-bin;
	}
}
