server {
	listen 4242;
	host 127.0.0.1;
	server_name localhost;

	root ./var/www/website;
	index index.html;

	client_max_body_size 10M;

	error_page 404 /404.html;
	error_page 500 /500.html;

	location /uploads {
		methods GET POST DELETE;
		root ./var/www/uploads;
		upload_store ./var/www/uploads;
		autoindex on;
	}

	location /cgi {
		methods GET POST;
		cgi_extension .py /usr/bin/python3;
		root ./var/www/cgi/cgi-bin;
	}

	location /redirect {
		return 301 http://example.com;
	}

	location /api {
		methods GET POST DELETE;
		root /var/www/api;
		index index.json;
	}
}

server {
	listen 8080;
	host 0.0.0.0;
	server_name example.com;

	root ./var/www/website;
	index yaaqoub.html;
	# content_type mp4;
	client_max_body_size 5M;

	location / {
		methods GET;
		autoindex off;
	}
}
